sudo: required
dist: trusty

language: cpp
compiler:
  - clang
  - gcc

env:
  - QTVER=5.10.1

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 -y
  - sudo apt-get install qt510-meta-minimal -y

script:
  - source /opt/qt510/bin/qt510-env.sh
  - qmake
  - make
