sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
#  - clang

env:
  - QTVER=5.10.1

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 -y
  - sudo apt-get install qt510-meta-minimal -y
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-7" CC="gcc-7"; fi
  - source /opt/qt510/bin/qt510-env.sh
  - wget https://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.10.4/QScintilla_gpl-2.10.4.tar.gz
  - tar -xvzf QScintilla_gpl-2.10.4.tar.gz
  - cd QScintilla_gpl-2.10.4/Qt4Qt5
  - qmake
  - make
  - sudo make install
  - cd ../..

script:
  - qmake -v
  - qmake
  - make
